### ISSUE TITLE
Can't view videos,images or reviews in the store 

### ISSUE THREAD

**Issue by TyShur** [ShadowMonster99/Simply-Dark#1]
Hi , i really like this skin, the interface and coloration is the best but i can't views the videos or images media in the store  and the reviews are loading forever.
Anyway to fix that ?
Again nice app and nice skin, keep up the good work 
![Capture d’écran 2023-11-22 125718](https://github.com/ShadowMonster99/Simply-Dark/assets/22522015/867b03b3-539f-47a9-ac80-9139facfba04)
![Capture d’écran 2023-11-22 130116](https://github.com/ShadowMonster99/Simply-Dark/assets/22522015/5a39cf16-dbde-42ec-be53-9c47771f5f9b)

**Comment by clawdius** [comment]
Hi, I know this is late, but the problem was solved in c1d3248. I'll close this thread, thanks for reporting!
