### ISSUE TITLE
Search bar not displaying properly in the friends window

### ISSUE THREAD

**Issue by Patrxgt** [ShadowMonster99/Simply-Dark#14]
![obraz](https://github.com/ShadowMonster99/Simply-Dark/assets/62941214/c9eb1541-c87f-4b95-b6ec-c57197864603)
As you can see, instead of keeping proper theming, the search bar is changing it's looks back to the original state and "moves" themed text under itself after clicking on it. It's worth noting, that it is not an exact representation of this issue, since I've used a tool to obscure data for privacy purposes.

**Comment by clawdius** [comment]
Thanks for submitting the report, I've pulled a request to fix the problem.
