### ISSUE TITLE
Context menu visual bug

### ISSUE THREAD

**Issue by rh1nehart** [ShadowMonster99/Simply-Dark#20]
![image](https://github.com/ShadowMonster99/Simply-Dark/assets/145158585/22b92c7b-0e10-4e6c-bbb9-343491578530)

There is no rounded corners on the top of context menu

**Comment by ShadowMonster99** [comment]
It’s a steam issue that isn’t immediately fixable. restarting steam will fix it, although temporarily until the next time steam bugs.
