### ISSUE TITLE
Artworks and screenshots section of the Steam Community page don't work properly

### ISSUE THREAD

**Issue by Patrxgt** [ShadowMonster99/simply-dark#25]
Here's the image of the issue:
![obraz](https://github.com/user-attachments/assets/66d63671-0e5d-4dc4-977c-064e32b97d70)

Every other theme I've tried didn't had such problem.

**Comment by clawdius** [comment]
Thanks for submitting the problem, I've pushed a fix for it, you can update the simply dark now. For reference, here is the looks of the fix:
![image](https://github.com/user-attachments/assets/9ea764d5-f11b-4f2e-8f60-abcf967c8154)

Let me know if this fix works for you, then I'll close the issue, thanks!

**Comment by Patrxgt** [comment]
Yup, that fixed it
