### ISSUE TITLE
[Feature request] Add dark theme to the Steam's Points Shop

### ISSUE THREAD

**Issue by Patrxgt** [ShadowMonster99/simply-dark#26]
The way it looks with Simply Dark theme applied:
![obraz](https://github.com/user-attachments/assets/6665c61c-1243-4563-87ef-428319b125ec)
The way it could look like (taken from the Minimal Dark theme):
![obraz](https://github.com/user-attachments/assets/0741c765-fd7e-48a8-8ad7-c0f798cc1882)

**Comment by clawdius** [comment]
Hello, I've pushed the update to fix the steam points shop theming, please refer to this picture below for the new looks

![image](https://github.com/user-attachments/assets/b2ac21d1-d8f5-4845-9d13-6a0410dc49b0)

Thank you for submitting the request!
