### ISSUE TITLE
Steam Friends

### ISSUE THREAD

**Issue by STiKster** [ShadowMonster99/simply-dark#35]
Please add a button at the top left of the main page to open the friend's tab. Also, in the "favourite area" under the username, there's no way to tell if a user is online or offline. Could you make it possible for online friends to have a green box around their avatars so we can easily tell if they are online or offline?

**Comment by clawdius** [comment]
1. I have no idea what you mean by "friend's tab", if you mean by friend's chat, why add another button other than the top right.
![image](https://github.com/user-attachments/assets/45628ee4-7978-4abc-ab7c-174427f0f478)

2. I think you can easily see who's in-game, online, and offline in the favorite menu under the username in friend's tab, for example, mine is like this
![image](https://github.com/user-attachments/assets/d91c49df-e6da-465f-bdd2-a00f745d24b7)

**Comment by clawdius** [comment]
Ah, you mean something like this?

![image](https://github.com/user-attachments/assets/2639191d-9a76-46f3-851f-0d2ece83088a)

**Comment by STiKster** [comment]
**Yeah, that's exactly what I want. I take it, but I need to edit the configuration. I had a quick look at them, but I didn't want to change anything just in case I ran into issues. What do I need to edit to get it like this**

![359830786-2639191d-9a76-46f3-851f-0d2ece83088a](https://github.com/user-attachments/assets/58fa5e15-d1fd-41d6-8a27-88748bccbff2)

**Comment by clawdius** [comment]
Alright, I've pushed an update, you can show the friends status by enabling the option in setting, please update your Simply Dark.

![image](https://github.com/user-attachments/assets/47cb2722-7b0c-4440-bd13-9fd4f4f71eed)

If you choose to enable, the favorite compact friends will look something like this

![image](https://github.com/user-attachments/assets/8d848274-4c5f-4304-88c0-b4a80200551f)

Let me know if you're still having trouble or need something else. If you satisfied, I'll close the issue.

**Comment by STiKster** [comment]
How do I update to the latest version?

**Comment by STiKster** [comment]
Yep, all sorted. Thank you for your help. It's much easier to see when my friends are online.

**Comment by STiKster** [comment]
I have an idea. Please add a gear cog for settings here. (The icon I attached is what I created. If you wish to proceed with the idea, you are more than welcome to use it.)

![Screenshot 2024-08-21 135703](https://github.com/user-attachments/assets/388053cd-c359-44d1-97a3-0ae968bbd491)

![GearCogIcon](https://github.com/user-attachments/assets/756634b1-bbba-420f-979c-1f710fca1c2d)

**Comment by clawdius** [comment]
> I have an idea. Please add a gear cog for settings here. (The icon I attached is what I created. If you wish to proceed with the idea, you are more than welcome to use it.)
> 
> ![Screenshot 2024-08-21 135703](https://private-user-images.githubusercontent.com/163735042/359905554-388053cd-c359-44d1-97a3-0ae968bbd491.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDcxNzksIm5iZiI6MTcyNDI0Njg3OSwicGF0aCI6Ii8xNjM3MzUwNDIvMzU5OTA1NTU0LTM4ODA1M2NkLWMzNTktNDRkMS05N2EzLTBhZTk2OGJiZDQ5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzI3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDg1NTA5YzVhZWFjNmQ3Y2I1NWExMjM5MjNhOWE2Y2VjOTMyOGU5MTE2YjljZmQyNzY1ZTBlNmExNjM3ZGE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aC9HF2ZDF5qYFL_F9TTdkj05d9XrI9JdaqlMxJmtj9M)
> 
> ![GearCogIcon](https://private-user-images.githubusercontent.com/163735042/359907042-756634b1-bbba-420f-979c-1f710fca1c2d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDcxNzksIm5iZiI6MTcyNDI0Njg3OSwicGF0aCI6Ii8xNjM3MzUwNDIvMzU5OTA3MDQyLTc1NjYzNGIxLWJiYmEtNDIwZi05NzljLTFmNzEwZmNhMWMyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMzI3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2UxOTlhNGYwNTA0ZDkyODk3NzUxOTQ2YjBiODc3NGFhYzZmYWU0OWZhZDBjZDJjMDFhZjg4YzNhOWQzMDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ABUWidU6_9Loch_hfoHmvQtkWe6yIPpEtfhCzJUhSGo)

Well i think that's gotta be another topic, I'll close this thread regarding the friends status. Thanks for the suggestion!
