### ISSUE TITLE
Top right menu is overlapping

### ISSUE THREAD

**Issue by clawdius** [ShadowMonster99/Simply-Dark#8]
**The problem:**
Since the "add game", "manage download", and "friends" button location are absolute, whenever the wallet's characters are long enough, the "notification" and "view news" button overlaps with the 3 buttons above.

**Example:**
![steam bug](https://github.com/ShadowMonster99/Simply-Dark/assets/61589143/04a94a89-57dc-4226-b760-93167f0e426e)

**The possible solution:**
1. Use the wallet tab's width to offset the 3 buttons.
2. Hide the wallet amount.
3. Go broke, since "Rp.0" and "$0" have few characters.

**Comment by ShadowMonster99** [comment]
As far as I remember there is an option to disable showing the wallet in the skin settings when you click the pencil on the millennium interface.

**Comment by clawdius** [comment]
> As far as I remember there is an option to disable showing the wallet in the skin settings when you click the pencil on the millennium interface.

of course, it was me that added the **forbidden broke feature**.
but i post this problem for the people with currency that has many characters such as Rupiah and still want to display their wallet amount.
